sudo: false
language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

env:
  - FLASK_VERSION=0.9
  - FLASK_VERSION=0.10.1

matrix:
  exclude:
    - python: "3.2"
      env: FLASK_VERSION=0.9
    - python: "3.3"
      env: FLASK_VERSION=0.9
    - python: "3.4"
      env: FLASK_VERSION=0.9

install:
  - pip install Flask==$FLASK_VERSION

script:
  - python setup.py test


