name: Pyrollbar CI

on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, '3.10', 3.11, 3.12, 3.13, 3.14]
        framework:
          - NONE
          - FLASK_VERSION=2.3.3
          - FLASK_VERSION=3.1.2
          - DJANGO_VERSION=4.2.25
          - DJANGO_VERSION=5.2.7
          - PYRAMID_VERSION=1.10.8
          - PYRAMID_VERSION=2.0.2
          - FASTAPI_VERSION=0.115.1 httpx==0.27.2 python-multipart==0.0.12
          - FASTAPI_VERSION=0.118.3 httpx==0.28.1 python-multipart==0.0.20
        exclude:
          # Test frameworks on the python versions they support, according to pypi registry

          # Django
          - framework: DJANGO_VERSION=5.2.7
            python-version: 3.9

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python Test dependencies
        run: pip install requests webob blinker httpx

      - name: Set the framework
        if: ${{ matrix.framework != 'NONE' }}
        run: echo ${{ matrix.framework }} >> $GITHUB_ENV

      - name: Install Flask
        if: ${{ contains(matrix.framework, 'FLASK_VERSION') }}
        run: pip install Flask==$FLASK_VERSION

      - name: Install Twisted
        if: ${{ contains(matrix.framework, 'TWISTED_VERSION') }}
        run: pip install Twisted==$TWISTED_VERSION idna==2.10

      - name: Install Django
        if: ${{ contains(matrix.framework, 'DJANGO_VERSION') }}
        run: pip install Django==$DJANGO_VERSION

      - name: Install Pyramid
        if: ${{ contains(matrix.framework, 'PYRAMID_VERSION') }}
        run: pip install pyramid==$PYRAMID_VERSION

      - name: Install Starlette
        if: ${{ contains(matrix.framework, 'STARLETTE_VERSION') }}
        run: pip install starlette==$STARLETTE_VERSION

      - name: Install FastAPI
        if: ${{ contains(matrix.framework, 'FASTAPI_VERSION') }}
        run: pip install fastapi==$FASTAPI_VERSION

      - name: Run tests
        run: python -m unittest rollbar.test.discover
